version: '3.5'
services:
  tictactoe-api-server-backend:
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: tictactoe-api-server-backend
